### ISSUE TITLE
Node.js - document is not defined

### ISSUE THREAD

**Issue by oberstlynild** [ruyadorno/simple-slider#46]
**THIS CODE**
```
var simpleslider = require('simple-slider');

simpleslider.getSlider({
	container: document.getElementById('news-content'),
	prop: 'opacity',
	unit: '',
	init: 0,
	show: 1,
	end: 0,
	duration: 0.5,
	delay: 10, //HVOR LÆNGE NEWS SKAL VISES
});

router.get('/', function(req, res, next) {
	res.render('index', {
		title: 'Frontpage',
		data: data,
		moment: moment,
		simpleslider: simpleslider,
	});
});
```

**GIVES THIS ERROR**
\HIDDEN PATH\routes\index.js:8
        container: document.getElementById('news-content'),
                   ^

ReferenceError: _document is not defined_
    at Object.<anonymous> (HIDDEN PATH\routes\index.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (HIDDEN PATH\app.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ruyadorno** [comment]
@oberstlynild sorry for the confusion but this module is meant for usage only in the context of a browser, it does not support Node.js (or a server-side rendered) usage.
